### ISSUE TITLE
产品下架了怎么下载

### ISSUE THREAD

**Issue by gdtydm** [luosuohu/product#5]
app store 下架了，我应该怎么下载

**Comment by ladyrick** [comment]
同问

**Comment by Bellapinger** [comment]
同问

**Comment by gdtydm** [comment]
我申请苹果退款了。推荐用美网帐号下载 potatso lite 很好用 免费

**Comment by ladyrick** [comment]
我算是懂了，这个app是个山寨app，正经的shadowrocket只在美区有，国区都是各种山寨shadowrocket的，上架一段时间，骗一笔钱就跑了。所以大家还是去美区购买shadowrocket吧。

**Comment by L-GY** [comment]
退款也退不了，我已经在美区买了一个了

**Comment by AndersonBY** [comment]
各位被坑了的同志，发送邮件到：itunesstoresupportzhs@apple.com和苹果说明情况，带上订单号，就可以退款了，我已经收到苹果的退款了。各位可以试试，顺带投诉这个开发者。
